add procps package to install ps
Sometime, there is some needs of `ps` command.
Below, I will show the head of Error message I got.

	WARN  Your platform does not support checking process liveness so TDB disk locations cannot be reliably locked to prevent possible corruption due to unsafe multi-JVM usage
	java.io.IOException: Cannot run program "ps": error=2, No such file or directory
	        at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	        at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	        at org.apache.jena.tdb.sys.ProcessUtils.getProcessInfo(ProcessUtils.java:144)